[all]
k8s-test-01 ansible_user=manage ansible_host=10.19.5.185 ansible_port=5566
k8s-test-02 ansible_user=manage ansible_host=10.19.5.186 ansible_port=5566
k8s-test-03 ansible_user=manage ansible_host=10.19.5.187 ansible_port=5566

[kube_control_plane]
k8s-test-01

[etcd:children]
kube_control_plane

[kube_node]
k8s-test-02
k8s-test-03
