apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-postgre
  namespace: cnpg-system
spec:
  instances: 3
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "512MB"
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  storage:
    size: 2Gi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-postgre-monitor
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: cluster-postgre
  podMetricsEndpoints:
  - port: metrics